### ISSUE TITLE
Have README correctly state how to edit RandomSettingsGenerator.py for rolling with overrides.

### ISSUE THREAD

**Issue by Vodzilla** [matthewkirby/plando-random-settings#19]
README currently says to edit RandomSettingsGenerator.py to roll seeds with overrides but only lists multiworld and DDR (although the process is the same for all overrides).  It says to remove `# ` from lines 16 and 17 but those lines don't match up with the multiworld and DDR overrides.  Simple fix.

Also in RandomSettingsGenerator.py the default weight file is described as Season 2 when it should be Season 3.

**Comment by matthewkirby** [comment]
Fixed. Thanks for pointing this out
